.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH rchip 1 "March 10, 2011" "" "Remote Controlled Homeautomation Integration Project"

.SH NAME
rchip \- A program for controling processes and devices from remote devices

.SH SYNOPSIS
.B rchip
.RI [ options ]
.br

.SH DESCRIPTION
rchip is a program designed to allow the user to control aspects of there computer from remote devices, as well as a protocol for control remote devices, and other computers from your desktop



.SH OPTIONS
.TP
.BI \-v, \-\-version
Displays Bersion Information
.TP
.BI \-h, \-\-help
Displays help information

.PP
Copyright 2010 Noside Racing, Inc.
